export const currency_list = [
    { value: 'USD', name: 'US Dollar (USD $)' },
    { value: 'EUR', name: 'Euro (EUR €)' },
    { value: 'GBP', name: 'British Pound (GBP £)' },
    { value: 'CAD', name: 'Canadian Dollar (CAD $)' },
    { value: 'AFN', name: 'Afghan Afghani (AFN ؋)' },
    { value: 'ALL', name: 'Albanian Lek (ALL)' },
    { value: 'DZD', name: 'Algerian Dinar (DZD)' },
    { value: 'AOA', name: 'Angolan Kwanza (AOA Kz)' },
    { value: 'ARS', name: 'Argentine Peso (ARS $)' },
    { value: 'AMD', name: 'Armenian Dram (AMD ֏)' },
    { value: 'AWG', name: 'Aruban Florin (AWG)' },
    { value: 'AUD', name: 'Australian Dollar (AUD $)' },
    { value: 'BBD', name: 'Barbadian Dollar (BBD $)' },
    { value: 'AZN', name: 'Azerbaijani Manat (AZN ₼)' },
    { value: 'BDT', name: 'Bangladeshi Taka (BDT ৳)' },
    { value: 'BSD', name: 'Bahamian Dollar (BSD $)' },
    { value: 'BHD', name: 'Bahraini Dinar (BHD)' },
    { value: 'BIF', name: 'Burundian Franc (BIF)' },
    { value: 'BYN', name: 'Belarusian Ruble (BYN)' },
    { value: 'BZD', name: 'Belize Dollar (BZD $)' },
    { value: 'BMD', name: 'Bermudan Dollar (BMD $)' },
    { value: 'BTN', name: 'Bhutanese Ngultrum (BTN)' },
    { value: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark (BAM KM)' },
    { value: 'BRL', name: 'Brazilian Real (BRL R$)' },
    { value: 'BOB', name: 'Bolivian Boliviano (BOB Bs)' },
    { value: 'BWP', name: 'Botswanan Pula (BWP P)' },
    { value: 'BND', name: 'Brunei Dollar (BND $)' },
    { value: 'BGN', name: 'Bulgarian Lev (BGN)' },
    { value: 'MMK', name: 'Myanmar Kyat (MMK K)' },
    { value: 'KHR', name: 'Cambodian Riel (KHR ៛)' },
    { value: 'CVE', name: 'Cape Verdean Escudo (CVE)' },
    { value: 'KYD', name: 'Cayman Islands Dollar (KYD $)' },
    { value: 'XAF', name: 'Central African CFA Franc (XAF FCFA)' },
    { value: 'CLP', name: 'Chilean Peso (CLP $)' },
    { value: 'CNY', name: 'Chinese Yuan (CNY ¥)' },
    { value: 'COP', name: 'Colombian Peso (COP $)' },
    { value: 'KMF', name: 'Comorian Franc (KMF CF)' },
    { value: 'CDF', name: 'Congolese Franc (CDF)' },
    { value: 'CRC', name: 'Costa Rican Colón (CRC ₡)' },
    { value: 'HRK', name: 'Croatian Kuna (HRK kn)' },
    { value: 'CZK', name: 'Czech Koruna (CZK Kč)' },
    { value: 'DKK', name: 'Danish Krone (DKK kr)' },
    { value: 'DJF', name: 'Djiboutian Franc (DJF)' },
    { value: 'DOP', name: 'Dominican Peso (DOP $)' },
    { value: 'XCD', name: 'East Caribbean Dollar (XCD $)' },
    { value: 'EGP', name: 'Egyptian Pound (EGP E£)' },
    { value: 'ERN', name: 'Eritrean Nakfa (ERN)' },
    { value: 'ETB', name: 'Ethiopian Birr (ETB)' },
    { value: 'FKP', name: 'Falkland Islands Pound (FKP £)' },
    { value: 'XPF', name: 'CFP Franc (XPF CFPF)' },
    { value: 'FJD', name: 'Fijian Dollar (FJD $)' },
    { value: 'GIP', name: 'Gibraltar Pound (GIP £)' },
    { value: 'GMD', name: 'Gambian Dalasi (GMD)' },
    { value: 'GHS', name: 'Ghanaian Cedi (GHS ₵)' },
    { value: 'GTQ', name: 'Guatemalan Quetzal (GTQ Q)' },
    { value: 'GYD', name: 'Guyanaese Dollar (GYD $)' },
    { value: 'GEL', name: 'Georgian Lari (GEL ₾)' },
    { value: 'GNF', name: 'Guinean Franc (GNF FG)' },
    { value: 'HTG', name: 'Haitian Gourde (HTG)' },
    { value: 'HNL', name: 'Honduran Lempira (HNL L)' },
    { value: 'HKD', name: 'Hong Kong Dollar (HKD HK$)' },
    { value: 'HUF', name: 'Hungarian Forint (HUF Ft)' },
    { value: 'ISK', name: 'Icelandic Króna (ISK kr)' },
    { value: 'INR', name: 'Indian Rupee (INR ₹)' },
    { value: 'IDR', name: 'Indonesian Rupiah (IDR Rp)' },
    { value: 'ILS', name: 'Israeli New Shekel (ILS ₪)' },
    { value: 'IRR', name: 'Iranian Rial (IRR)' },
    { value: 'IQD', name: 'Iraqi Dinar (IQD)' },
    { value: 'JMD', name: 'Jamaican Dollar (JMD $)' },
    { value: 'JPY', name: 'Japanese Yen (JPY ¥)' },
    { value: 'JEP', name: 'Jersey Pound (JEP)' },
    { value: 'JOD', name: 'Jordanian Dinar (JOD)' },
    { value: 'KZT', name: 'Kazakhstani Tenge (KZT ₸)' },
    { value: 'KES', name: 'Kenyan Shilling (KES)' },
    { value: 'KID', name: 'Kiribati Dollar (KID)' },
    { value: 'KWD', name: 'Kuwaiti Dinar (KWD)' },
    { value: 'KGS', name: 'Kyrgystani Som (KGS ⃀)' },
    { value: 'LAK', name: 'Laotian Kip (LAK ₭)' },
    { value: 'LVL', name: 'Latvian Lats (LVL)' },
    { value: 'LBP', name: 'Lebanese Pound (LBP L£)' },
    { value: 'LSL', name: 'Lesotho Loti (LSL)' },
    { value: 'LRD', name: 'Liberian Dollar (LRD $)' },
    { value: 'LYD', name: 'Libyan Dinar (LYD)' },
    { value: 'LTL', name: 'Lithuanian Litas (LTL)' },
    { value: 'MGA', name: 'Malagasy Ariary (MGA Ar)' },
    { value: 'MKD', name: 'Macedonian Denar (MKD)' },
    { value: 'MOP', name: 'Macanese Pataca (MOP)' },
    { value: 'MWK', name: 'Malawian Kwacha (MWK)' },
    { value: 'MVR', name: 'Maldivian Rufiyaa (MVR)' },
    { value: 'MRU', name: 'Mauritanian Ouguiya (MRU)' },
    { value: 'MXN', name: 'Mexican Peso (MXN $)' },
    { value: 'MYR', name: 'Malaysian Ringgit (MYR RM)' },
    { value: 'MUR', name: 'Mauritian Rupee (MUR Rs)' },
    { value: 'MDL', name: 'Moldovan Leu (MDL)' },
    { value: 'MAD', name: 'Moroccan Dirham (MAD)' },
    { value: 'MNT', name: 'Mongolian Tugrik (MNT ₮)' },
    { value: 'MZN', name: 'Mozambican Metical (MZN)' },
    { value: 'NAD', name: 'Namibian Dollar (NAD $)' },
    { value: 'NPR', name: 'Nepalese Rupee (NPR Rs)' },
    { value: 'ANG', name: 'Netherlands Antillean Guilder (ANG)' },
    { value: 'NZD', name: 'New Zealand Dollar (NZD $)' },
    { value: 'NIO', name: 'Nicaraguan Córdoba (NIO C$)' },
    { value: 'NGN', name: 'Nigerian Naira (NGN ₦)' },
    { value: 'NOK', name: 'Norwegian Krone (NOK kr)' },
    { value: 'OMR', name: 'Omani Rial (OMR)' },
    { value: 'PAB', name: 'Panamanian Balboa (PAB)' },
    { value: 'PKR', name: 'Pakistani Rupee (PKR Rs)' },
    { value: 'PGK', name: 'Papua New Guinean Kina (PGK)' },
    { value: 'PYG', name: 'Paraguayan Guarani (PYG ₲)' },
    { value: 'PEN', name: 'Peruvian Sol (PEN)' },
    { value: 'PHP', name: 'Philippine Piso (PHP ₱)' },
    { value: 'PLN', name: 'Polish Zloty (PLN zł)' },
    { value: 'QAR', name: 'Qatari Rial (QAR)' },
    { value: 'RON', name: 'Romanian Leu (RON lei)' },
    { value: 'RUB', name: 'Russian Ruble (RUB ₽)' },
    { value: 'RWF', name: 'Rwandan Franc (RWF RF)' },
    { value: 'WST', name: 'Samoan Tala (WST)' },
    { value: 'SHP', name: 'St. Helena Pound (SHP £)' },
    { value: 'SAR', name: 'Saudi Riyal (SAR)' },
    { value: 'RSD', name: 'Serbian Dinar (RSD)' },
    { value: 'SCR', name: 'Seychellois Rupee (SCR)' },
    { value: 'SLL', name: 'Sierra Leonean Leone (SLL)' },
    { value: 'SGD', name: 'Singapore Dollar (SGD $)' },
    { value: 'SDG', name: 'Sudanese Pound (SDG)' },
    { value: 'SOS', name: 'Somali Shilling (SOS)' },
    { value: 'SYP', name: 'Syrian Pound (SYP £)' },
    { value: 'ZAR', name: 'South African Rand (ZAR R)' },
    { value: 'KRW', name: 'South Korean Won (KRW ₩)' },
    { value: 'SSP', name: 'South Sudanese Pound (SSP £)' },
    { value: 'SBD', name: 'Solomon Islands Dollar (SBD $)' },
    { value: 'LKR', name: 'Sri Lankan Rupee (LKR Rs)' },
    { value: 'SRD', name: 'Surinamese Dollar (SRD $)' },
    { value: 'SZL', name: 'Swazi Lilangeni (SZL)' },
    { value: 'SEK', name: 'Swedish Krona (SEK kr)' },
    { value: 'CHF', name: 'Swiss Franc (CHF)' },
    { value: 'TWD', name: 'New Taiwan Dollar (TWD $)' },
    { value: 'THB', name: 'Thai Baht (THB ฿)' },
    { value: 'TJS', name: 'Tajikistani Somoni (TJS)' },
    { value: 'TZS', name: 'Tanzanian Shilling (TZS)' },
    { value: 'TOP', name: 'Tongan Paʻanga (TOP T$)' },
    { value: 'TTD', name: 'Trinidad &amp; Tobago Dollar (TTD $)' },
    { value: 'TND', name: 'Tunisian Dinar (TND)' },
    { value: 'TRY', name: 'Turkish Lira (TRY ₺)' },
    { value: 'TMT', name: 'Turkmenistani Manat (TMT)' },
    { value: 'UGX', name: 'Ugandan Shilling (UGX)' },
    { value: 'UAH', name: 'Ukrainian Hryvnia (UAH ₴)' },
    { value: 'AED', name: 'United Arab Emirates Dirham (AED)' },
    { value: 'UYU', name: 'Uruguayan Peso (UYU $)' },
    { value: 'UZS', name: 'Uzbekistani Som (UZS)' },
    { value: 'VUV', name: 'Vanuatu Vatu (VUV)' },
    { value: 'VES', name: 'Venezuelan Bolívar (VES)' },
    { value: 'VND', name: 'Vietnamese Dong (VND ₫)' },
    { value: 'XOF', name: 'West African CFA Franc (XOF F CFA)' },
    { value: 'YER', name: 'Yemeni Rial (YER)' },
    { value: 'ZMW', name: 'Zambian Kwacha (ZMW ZK)' },
    { value: 'BYR', name: 'Belarusian Ruble (2000–2016) (BYR)' },
    { value: 'STD', name: 'São Tomé &amp; Príncipe Dobra (1977–2017) (STD)' },
    { value: 'STN', name: 'São Tomé &amp; Príncipe Dobra (STN Db)' },
    { value: 'VEF', name: 'Venezuelan Bolívar (2008–2018) (VEF)' },
    { value: 'XXX', name: 'Unknown Currency (XXX)' },
    { value: 'VED', name: 'VED (VED)' },
];
